sudo: require

service:
  - docker

before_install:
  - docker build -t r4ncid/config-service -f ./Dockerfile.dev .

script:
  - docker run r4ncid/config-service yarn test


after_success:
  #Build the docker file
  - docker build -t r4ncid/config-service .
  - docker push r4ncid/config-service
